INSERT INTO `v9_category` VALUES('1','1','content','1','0','0','0','1','1,14,2,3,15,4,6,7,67','智美达人','','','','','about','/html/about/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'zmodo\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','1','0','zhimeidaren','');
INSERT INTO `v9_category` VALUES('2','1','content','1','0','1','0,1','0','2','公司使命','','','','about/','target','/html/about/target/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'zmodo\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'关于我们\',
  \'meta_keywords\' => \'关于我们\',
  \'meta_description\' => \'关于我们\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','2','1','0','gongsishiming','');
INSERT INTO `v9_category` VALUES('3','1','content','1','0','1','0,1','0','3','经营理念','','','','about/','strategy','/html/about/strategy/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'zmodo\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'联系方式\',
  \'meta_keywords\' => \'联系方式\',
  \'meta_description\' => \'联系方式\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','3','1','0','jingyinglinian','');
INSERT INTO `v9_category` VALUES('4','1','content','1','0','1','0,1','0','4','组织架构','','','','about/','framework','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=4','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'版权声明\',
  \'meta_keywords\' => \'版权声明\',
  \'meta_description\' => \'版权声明\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','5','1','0','zuzhijiagou','');
INSERT INTO `v9_category` VALUES('6','1','content','0','1','1','0,1','0','6','新闻动态','','','','about/','news','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=6','8','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','6','1','0','xinwendongtai','');
INSERT INTO `v9_category` VALUES('7','1','content','0','3','1','0,1','0','7','员工风采','','','','about/','show','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=7','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','7','1','0','yuangongfengcai','');
INSERT INTO `v9_category` VALUES('8','1','content','0','1','11','0,11','1','8,23,63','商业发展','','','','share/','business','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=8','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','8','1','0','shangyefazhan','');
INSERT INTO `v9_category` VALUES('9','1','content','0','2','11','0,11','1','9,27,28,31,32,58,33,34,35,36,55,56,59,37,39,40,41,38,42,43,29,44,47,45,48,49,46,50,51,30,52,53,54,57','市场与销售','','','','share/','marketingsales','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=9','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','9','1','0','shichangyuxiaoshou','');
INSERT INTO `v9_category` VALUES('10','1','content','0','1','11','0,11','1','10,20,21,22','产品中心','','','','share/','prodcuts','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=10','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','10','1','0','chanpinzhongxin','');
INSERT INTO `v9_category` VALUES('11','1','content','0','2','0','0','1','11,8,23,63,9,27,28,31,32,58,33,34,35,36,55,56,59,37,39,40,41,38,42,43,29,44,47,45,48,49,46,50,51,30,52,53,54,57,10,20,21,22,12,13,16,69','资源共享','','','','','share','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=11','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','3','1','0','ziyuangongxiang','');
INSERT INTO `v9_category` VALUES('12','1','content','0','2','11','0,11','0','12','IT','','','','share/','it','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=12','10','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','12','1','0','it','');
INSERT INTO `v9_category` VALUES('13','1','content','0','2','11','0,11','0','13','财务部','','','','share/','Finance','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=13','7','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','13','1','0','caiwubu','');
INSERT INTO `v9_category` VALUES('28','1','content','0','2','27','0,11,9,27','1','28,31,32,58,33,34,35,36,55,56,59,37,39,40,41,38,42,43','售前','','','','share/marketingsales/xsgjb/','presales','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=28','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','28','1','0','shouqian','');
INSERT INTO `v9_category` VALUES('29','1','content','0','2','27','0,11,9,27','1','29,44,47,45,48,49,46,50,51','售中','','','','share/marketingsales/xsgjb/','midsales','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=29','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','29','1','0','shouzhong','');
INSERT INTO `v9_category` VALUES('14','1','content','1','0','1','0,1','0','14','董事长致辞','','','','about/','DSZZC','/html/about/DSZZC/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'zmodo\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','1','1','0','dongshichangzhici','');
INSERT INTO `v9_category` VALUES('15','1','content','1','0','1','0,1','0','15','公司价值观','','','','about/','GSJZG','/html/about/GSJZG/','0','0','array (
  \'ishtml\' => \'1\',
  \'template_list\' => \'zmodo\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'1\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','4','1','0','gongsijiazhiguan','');
INSERT INTO `v9_category` VALUES('16','1','content','0','2','11','0,11','1','16,69','人事行政','','','','share/','RSXZ','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=16','40','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','16','1','0','renshixingzheng','');
INSERT INTO `v9_category` VALUES('27','1','content','0','2','9','0,11,9','1','27,28,31,32,58,33,34,35,36,55,56,59,37,39,40,41,38,42,43,29,44,47,45,48,49,46,50,51,30,52,53,54','销售工具包','','','','share/marketingsales/','xsgjb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=27','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','27','0','0','xiaoshougongjubao','');
INSERT INTO `v9_category` VALUES('20','1','content','0','2','10','0,11,10','0','20','产品生产链','','','','share/prodcuts/','CPSCL','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=20','19','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','20','1','0','chanpinshengchanlian','');
INSERT INTO `v9_category` VALUES('21','1','content','0','2','10','0,11,10','0','21','深圳研发','','','','share/prodcuts/','SZRD','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=21','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','21','1','0','shenzuoyanfa','');
INSERT INTO `v9_category` VALUES('22','1','content','0','2','10','0,11,10','0','22','北京研发','','','','share/prodcuts/','BJRD','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=22','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','22','1','0','beijingyanfa','');
INSERT INTO `v9_category` VALUES('23','1','content','0','1','8','0,11,8','0','23','投融资部','','','','share/business/','TRZB','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=23','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','23','1','0','tourongzibu','');
INSERT INTO `v9_category` VALUES('24','1','content','0','1','0','0','0','24','大家的分享','','','','','zmodoer_share','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=24','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','24','0','0','dajiadefenxiang','');
INSERT INTO `v9_category` VALUES('25','1','content','0','1','0','0','1','25,64,65','知识库','','','','','kb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=25','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','25','1','0','zhishiku','');
INSERT INTO `v9_category` VALUES('26','1','content','0','1','0','0','1','26,66','员工关怀','','','','','care','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=26','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_menushow\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','26','0','0','yuangongguanhuai','');
INSERT INTO `v9_category` VALUES('69','1','content','0','1','16','0,11,16','0','69','规章制度','','','','share/RSXZ/','gzzd','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=69','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','69','1','0','guizhangzhidu','');
INSERT INTO `v9_category` VALUES('30','1','content','0','2','27','0,11,9,27','1','30,52,53,54','售后','','','','share/marketingsales/xsgjb/','aftersales','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=30','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','30','1','0','shouhou','');
INSERT INTO `v9_category` VALUES('55','1','content','0','2','33','','0','55','行业协会','','','','/','hyxh','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=55','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','55','1','0','xingyexiehui','');
INSERT INTO `v9_category` VALUES('31','1','content','0','2','28','0,11,9,27,28','1','31,32,58,33,34,35,36,55,56,59','公司介绍','','','','share/marketingsales/xsgjb/presales/','gsjs','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=31','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','31','1','0','gongsijieshao','');
INSERT INTO `v9_category` VALUES('32','1','content','0','2','31','','0','32','PPT形式公司介绍','','','','/','pptgsjs','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=32','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','32','1','0','pptxingshigongsijieshao','');
INSERT INTO `v9_category` VALUES('33','1','content','0','2','31','','1','33,34,35,36,55,56,59','公司资质','','','','/','gszz','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=33','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','58','1','0','gongsizizhi','');
INSERT INTO `v9_category` VALUES('34','1','content','0','2','33','','0','34','公司三证和银行账户','','','','/','gsszhyhzh','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=34','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','34','1','0','gongsisanzhengheyinxingzhanghu','');
INSERT INTO `v9_category` VALUES('35','1','content','0','2','33','','0','35','公司荣誉证书','','','','/','gsryzs','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=35','33','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','35','1','0','gongsirongyuzhengshu','');
INSERT INTO `v9_category` VALUES('36','1','content','0','2','33','','0','36','公司认证和报告','','','','/','gsrzbg','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=36','6','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','36','1','0','gongsirenzhenghebaogao','');
INSERT INTO `v9_category` VALUES('37','1','content','0','2','28','0,11,9,27,28','1','37,39,40,41','产品目录','','','','share/marketingsales/xsgjb/presales/','chanpinmulu','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=37','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','37','1','0','chanpinmulu','');
INSERT INTO `v9_category` VALUES('38','1','content','0','2','28','0,11,9,27,28','1','38,42,43','产品价格体系表','','','','share/marketingsales/xsgjb/presales/','cpjgtxb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=38','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','38','1','0','chanpinjiagetixibiao','');
INSERT INTO `v9_category` VALUES('39','1','content','0','2','37','','0','39','电商平台产品','','','','/','dsptcp','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=39','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','39','1','0','dianshangpingtaichanpin','');
INSERT INTO `v9_category` VALUES('40','1','content','0','2','37','','0','40','渠道产品','','','','/','qdcp','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=40','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','40','1','0','qudaochanpin','');
INSERT INTO `v9_category` VALUES('41','1','content','0','2','37','','0','41','工程产品','','','','/','gccp','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=41','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','41','1','0','gongchengchanpin','');
INSERT INTO `v9_category` VALUES('42','1','content','0','2','38','','0','42','渠道价格体系表','','','','/','qudaojgtxb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=42','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','42','1','0','qudaojiagetixibiao','');
INSERT INTO `v9_category` VALUES('43','1','content','0','2','38','','0','43','工程价格体系表','','','','/','gongcjgtxb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=43','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','43','1','0','gongchengjiagetixibiao','');
INSERT INTO `v9_category` VALUES('44','1','content','0','2','29','0,11,9,27,29','1','44,47','合同管理','','','','share/marketingsales/xsgjb/midsales/','htgl','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=44','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','44','1','0','hetongguanli','');
INSERT INTO `v9_category` VALUES('45','1','content','0','2','29','0,11,9,27,29','1','45,48,49','订单管理','','','','share/marketingsales/xsgjb/midsales/','ddgl','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=45','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','45','1','0','dingdanguanli','');
INSERT INTO `v9_category` VALUES('46','1','content','0','2','29','0,11,9,27,29','1','46,50,51','客户管理','','','','share/marketingsales/xsgjb/midsales/','khgl','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=46','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','46','1','0','kehuguanli','');
INSERT INTO `v9_category` VALUES('47','1','content','0','2','44','','0','47','合同模板','','','','/','htmb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=47','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','47','1','0','hetongmoban','');
INSERT INTO `v9_category` VALUES('48','1','content','0','2','45','','0','48','订单流程表','','','','/','ddlcb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=48','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','48','1','0','dingdanliuchengbiao','');
INSERT INTO `v9_category` VALUES('49','1','content','0','2','45','','0','49','订单模板','','','','/','ddmb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=49','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','49','1','0','dingdanmoban','');
INSERT INTO `v9_category` VALUES('50','1','content','0','2','46','','0','50','客户诚信管理','','','','/','kecxgl','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=50','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','50','1','0','kehuchengxinguanli','');
INSERT INTO `v9_category` VALUES('51','1','content','0','2','46','','0','51','客户信息管理','','','','/','khxxgl','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=51','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','51','1','0','kehuxinxiguanli','');
INSERT INTO `v9_category` VALUES('52','1','content','0','2','30','0,11,9,27,30','0','52','产品故障技术支持文件','','','','share/marketingsales/xsgjb/aftersales/','cpgzjszcwj','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=52','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','52','1','0','chanpinguzhangjishuzhichiwenji','');
INSERT INTO `v9_category` VALUES('53','1','content','0','2','30','0,11,9,27,30','0','53','产品技术升级支持包','','','','share/marketingsales/xsgjb/aftersales/','cpjssjzcb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=53','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','53','1','0','chanpinjishushengjizhichibao','');
INSERT INTO `v9_category` VALUES('54','1','content','0','2','30','0,11,9,27,30','0','54','RMA流程表','','','','share/marketingsales/xsgjb/aftersales/','rmalcb','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=54','3','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','54','1','0','rmaliuchengbiao','');
INSERT INTO `v9_category` VALUES('56','1','content','0','2','33','','0','56','ISO 9001认证','','','','/','iso9001rz','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=56','2','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','56','1','0','iso 9001renzheng','');
INSERT INTO `v9_category` VALUES('59','1','content','0','2','33','','0','59','产品生产登记证书','','','','/','cpscdjzs','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=59','4','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','59','1','0','chanpinshengchandengjizhengshu','');
INSERT INTO `v9_category` VALUES('57','1','content','0','2','9','0,11,9','0','57','销售工具包','','','','share/marketingsales/','sale','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=57','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'\',
  \'list_template\' => \'list_menushow\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','57','1','0','xiaoshougongjubao','');
INSERT INTO `v9_category` VALUES('58','1','content','0','2','31','','0','58','ZMODO视频资料','','','','/','zspzl','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=58','11','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category_download\',
  \'list_template\' => \'list_download\',
  \'show_template\' => \'show_download\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','33','1','0','zmodoshipinziliao','');
INSERT INTO `v9_category` VALUES('60','1','content','0','1','0','0','1','60,61,62,70,68','协同办公','','','','','xtbg','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=60','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','2','1','0','xietongbangong','');
INSERT INTO `v9_category` VALUES('61','1','content','2','0','60','','0','','项目管理','','','','','','http://172.18.19.254/project','0','0','array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','0','1','0','','');
INSERT INTO `v9_category` VALUES('62','1','content','2','0','60','','0','','ZMODO.CN邮件系统','','','','','','http://mail.zmodo.cn','0','0','array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','0','1','0','','');
INSERT INTO `v9_category` VALUES('63','1','content','1','0','8','0,11,8','0','63','行业动态','','','','share/business/','security_news','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=63','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','63','1','0','xingyedongtai','');
INSERT INTO `v9_category` VALUES('64','1','content','0','1','25','0,25','0','64','读书分享','','','2013管理干部第一期读书分享PPT，提升自我，缔造智美达高绩效团队！','kb/','shared_reading','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=64','14','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','64','1','0','dushufenxiang','');
INSERT INTO `v9_category` VALUES('65','1','content','0','1','25','0,25','0','65','产品知识','','','','kb/','product_knowledge','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=65','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','65','1','0','chanpinzhishi','');
INSERT INTO `v9_category` VALUES('66','1','content','0','3','26','0,26','0','66','员工生日会','','http://zone.zmodo.com/cms/uploadfile/2013/0426/20130426042312177.jpg','','care/','Employee_birthday','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=66','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','66','1','0','yuangongshengrihui','');
INSERT INTO `v9_category` VALUES('67','1','content','0','1','1','0,1','0','67','公司周刊','','','','about/','weekly','http://localhost/CMS/index.php?m=content&c=index&a=lists&catid=67','5','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'zmodo\',
  \'category_template\' => \'\',
  \'list_template\' => \'list\',
  \'show_template\' => \'\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','67','0','0','gongsizhoukan','');
INSERT INTO `v9_category` VALUES('70','1','content','2','0','60','','0','','Company Directory','','','','','','http://172.18.19.94/cms/index.php?m=cdsearch','0','0','array (
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','0','1','0','company directory','');
